distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Tue Apr  4 18:01:37 2017"
installation_id: "860dd7a6-9e8a-4b6c-a6f9-dc28e0ff6516"
rime_version: 1.2.9